export const PAGINATION_TRANSFORM_VALUE = 458;

export const PAGINATION_SMALL_TRANSFORM_VALUE = 227;

export const INITIAL_PAGINATION_ROWS_ARR = [5, 10, 15, 20];

export const INITIAL_PAGINATION_MORE_COUNT = 4;

export const INITIAL_PAGINATION_DATA_LENGTH = 30;

export const INITIAL_SUB_CATEGORY_TRANSFORM = 125;

export const INITIAL_PAGINATION_ACTIVE_PAGE = 0;

export const INITIAL_PAGINATION_ROWS_PER_PAGE = 4;

export const INITIAL_PAGINATION_RANGE_DISPLAYED = 2;

export const INITIAL_PAGINATION_MARGIN_DISPLAYED = 1;
