const filmsBase = [
  {
    filmName: '1 Coll film',
    viewsCount: '777',
    likeCount: '156',
    uploadDate: '22/15/26',
    commentsCount: '999',
    descriptionText: 'This video is property IDEO',
    globalTime: '5.00',
  },

  {
    filmName: 'Film qwerty',
    viewsCount: '777',
    likeCount: '156',
    uploadDate: '22/15/26',
    commentsCount: '999',
    descriptionText: 'This video is property IDEO',
    globalTime: '5.00',
  },

  {
    filmName: '2 Bad film',
    viewsCount: '156',
    likeCount: '753',
    uploadDate: '22/15/26',
    commentsCount: '333',
    descriptionText: 'This video is property IDEO',
    globalTime: '9.50',
  },

  {
    filmName: '3 Light film',
    viewsCount: '753',
    likeCount: '456',
    uploadDate: '22/15/26',
    commentsCount: '369',
    descriptionText: 'This video is property IDEO',
    globalTime: '1.15',
  },

  {
    filmName: '4 Coll light film',
    viewsCount: '159',
    likeCount: '753',
    uploadDate: '22/15/26',
    commentsCount: '888',
    descriptionText: 'This video is property IDEO',
    globalTime: '0.55',
  },
  {
    filmName: '5 Coll film',
    viewsCount: '654',
    likeCount: '456',
    uploadDate: '22/15/26',
    commentsCount: '159',
    descriptionText: 'This video is property IDEO',
    globalTime: '5.00',
  },
  {
    filmName: '6 Coll film',
    viewsCount: '777',
    likeCount: '156',
    uploadDate: '22/15/26',
    commentsCount: '999',
    descriptionText: 'This video is property IDEO',
    globalTime: '5.00',
  },
  {
    filmName: '7 Coll film',
    viewsCount: '777',
    likeCount: '156',
    uploadDate: '22/15/26',
    commentsCount: '999',
    descriptionText: 'This video is property IDEO',
    globalTime: '5.00',
  },
  {
    filmName: '8 Coll film',
    viewsCount: '777',
    likeCount: '156',
    uploadDate: '22/15/26',
    commentsCount: '999',
    descriptionText: 'This video is property IDEO',
    globalTime: '5.00',
  },
  {
    filmName: '9 Coll film',
    viewsCount: '777',
    likeCount: '156',
    uploadDate: '22/15/26',
    commentsCount: '999',
    descriptionText: 'This video is property IDEO',
    globalTime: '5.00',
  },
  {
    filmName: '10 Coll film',
    viewsCount: '777',
    likeCount: '156',
    uploadDate: '22/15/26',
    commentsCount: '999',
    descriptionText: 'This video is property IDEO',
    globalTime: '5.00',
  },

  {
    filmName: '11 Coll film',
    viewsCount: '777',
    likeCount: '156',
    uploadDate: '22/15/26',
    commentsCount: '999',
    descriptionText: 'This video is property IDEO',
    globalTime: '5.00',
  },
  {
    filmName: '12 Coll film',
    viewsCount: '777',
    likeCount: '156',
    uploadDate: '22/15/26',
    commentsCount: '999',
    descriptionText: 'This video is property IDEO',
    globalTime: '5.00',
  },
  {
    filmName: '13 Coll film',
    viewsCount: '777',
    likeCount: '156',
    uploadDate: '22/15/26',
    commentsCount: '999',
    descriptionText: 'This video is property IDEO',
    globalTime: '5.00',
  },
  {
    filmName: '14 Coll film',
    viewsCount: '777',
    likeCount: '156',
    uploadDate: '22/15/26',
    commentsCount: '999',
    descriptionText: 'This video is property IDEO',
    globalTime: '5.00',
  },

  {
    filmName: '15 Coll film',
    viewsCount: '777',
    likeCount: '156',
    uploadDate: '22/15/26',
    commentsCount: '999',
    descriptionText: 'This video is property IDEO',
    globalTime: '5.00',
  },
  {
    filmName: '16 Coll film',
    viewsCount: '777',
    likeCount: '156',
    uploadDate: '22/15/26',
    commentsCount: '999',
    descriptionText: 'This video is property IDEO',
    globalTime: '5.00',
  },

  {
    filmName: '17 Coll film',
    viewsCount: '777',
    likeCount: '156',
    uploadDate: '22/15/26',
    commentsCount: '999',
    descriptionText: 'This video is property IDEO',
    globalTime: '5.00',
  },
  {
    filmName: '18 Coll film',
    viewsCount: '777',
    likeCount: '156',
    uploadDate: '22/15/26',
    commentsCount: '999',
    descriptionText: 'This video is property IDEO',
    globalTime: '5.00',
  },
  {
    filmName: '19 Coll film',
    viewsCount: '777',
    likeCount: '156',
    uploadDate: '22/15/26',
    commentsCount: '999',
    descriptionText: 'This video is property IDEO',
    globalTime: '5.00',
  },
  {
    filmName: '20 Coll film',
    viewsCount: '777',
    likeCount: '156',
    uploadDate: '22/15/26',
    commentsCount: '999',
    descriptionText: 'This video is property IDEO',
    globalTime: '5.00',
  },
];

export default filmsBase;
