const staticBasa = [
  {
    filmName: 'Coll film',
    viewsCount: '777',
    likeCount: '156',
    uploadDate: '22/15/26',
    commentsCount: '999',
    descriptionText: 'This video is property IDEO',
    globalTime: '5.00',
  },

  {
    filmName: 'Bad film',
    viewsCount: '156',
    likeCount: '753',
    uploadDate: '22/15/26',
    commentsCount: '333',
    descriptionText: 'This video is property IDEO',
    globalTime: '9.50',
  },

  {
    filmName: 'Light film',
    viewsCount: '753',
    likeCount: '456',
    uploadDate: '22/15/26',
    commentsCount: '369',
    descriptionText: 'This video is property IDEO',
    globalTime: '1.15',
  },

  {
    filmName: 'Coll light film',
    viewsCount: '159',
    likeCount: '753',
    uploadDate: '22/15/26',
    commentsCount: '888',
    descriptionText: 'This video is property IDEO',
    globalTime: '0.55',
  },
  {
    filmName: 'Coll film',
    viewsCount: '654',
    likeCount: '456',
    uploadDate: '22/15/26',
    commentsCount: '159',
    descriptionText: 'This video is property IDEO',
    globalTime: '5.00',
  },
  {
    filmName: 'Coll film',
    viewsCount: '777',
    likeCount: '156',
    uploadDate: '22/15/26',
    commentsCount: '999',
    descriptionText: 'This video is property IDEO',
    globalTime: '5.00',
  },
  {
    filmName: 'Coll film',
    viewsCount: '777',
    likeCount: '156',
    uploadDate: '22/15/26',
    commentsCount: '999',
    descriptionText: 'This video is property IDEO',
    globalTime: '5.00',
  },
  {
    filmName: 'Coll film',
    viewsCount: '777',
    likeCount: '156',
    uploadDate: '22/15/26',
    commentsCount: '999',
    descriptionText: 'This video is property IDEO',
    globalTime: '5.00',
  },
  {
    filmName: 'Coll film',
    viewsCount: '777',
    likeCount: '156',
    uploadDate: '22/15/26',
    commentsCount: '999',
    descriptionText: 'This video is property IDEO',
    globalTime: '5.00',
  },
  {
    filmName: 'Coll film',
    viewsCount: '777',
    likeCount: '156',
    uploadDate: '22/15/26',
    commentsCount: '999',
    descriptionText: 'This video is property IDEO',
    globalTime: '5.00',
  },

  {
    filmName: 'Coll film',
    viewsCount: '777',
    likeCount: '156',
    uploadDate: '22/15/26',
    commentsCount: '999',
    descriptionText: 'This video is property IDEO',
    globalTime: '5.00',
  },
  {
    filmName: 'Coll film',
    viewsCount: '777',
    likeCount: '156',
    uploadDate: '22/15/26',
    commentsCount: '999',
    descriptionText: 'This video is property IDEO',
    globalTime: '5.00',
  },
  {
    filmName: 'Coll film',
    viewsCount: '777',
    likeCount: '156',
    uploadDate: '22/15/26',
    commentsCount: '999',
    descriptionText: 'This video is property IDEO',
    globalTime: '5.00',
  },
  {
    filmName: 'Coll film',
    viewsCount: '777',
    likeCount: '156',
    uploadDate: '22/15/26',
    commentsCount: '999',
    descriptionText: 'This video is property IDEO',
    globalTime: '5.00',
  },

  {
    filmName: 'Coll film',
    viewsCount: '777',
    likeCount: '156',
    uploadDate: '22/15/26',
    commentsCount: '999',
    descriptionText: 'This video is property IDEO',
    globalTime: '5.00',
  },
  {
    filmName: 'Coll film',
    viewsCount: '777',
    likeCount: '156',
    uploadDate: '22/15/26',
    commentsCount: '999',
    descriptionText: 'This video is property IDEO',
    globalTime: '5.00',
  },

  {
    filmName: 'Coll film',
    viewsCount: '777',
    likeCount: '156',
    uploadDate: '22/15/26',
    commentsCount: '999',
    descriptionText: 'This video is property IDEO',
    globalTime: '5.00',
  },
  {
    filmName: 'Coll film',
    viewsCount: '777',
    likeCount: '156',
    uploadDate: '22/15/26',
    commentsCount: '999',
    descriptionText: 'This video is property IDEO',
    globalTime: '5.00',
  },
  {
    filmName: 'Coll film',
    viewsCount: '777',
    likeCount: '156',
    uploadDate: '22/15/26',
    commentsCount: '999',
    descriptionText: 'This video is property IDEO',
    globalTime: '5.00',
  },
  {
    filmName: 'Coll film',
    viewsCount: '777',
    likeCount: '156',
    uploadDate: '22/15/26',
    commentsCount: '999',
    descriptionText: 'This video is property IDEO',
    globalTime: '5.00',
  },
];

export default staticBasa;
